### PR TITLE
Switch AwsCredentials to use the default auth chain

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
For reference this is the default implementation for AmazonS3Client (https://github.com/aws/aws-sdk-java/blob/1.11.15/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L400-L415), and we need this because we use IAM roles for our CI, not profile files. Thanks.

**Comment by fiadliel** [comment]
I think we can use `com.amazonaws.auth.DefaultAWSCredentialsProviderChain` instead?

The supported authentication methods seem to match:

> AWS credentials provider chain that looks for credentials in this order:
> - Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or AWS_ACCESS_KEY and AWS_SECRET_KEY (only recognized by Java SDK)
> - Java System Properties - aws.accessKeyId and aws.secretKey
> - Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
> - Instance profile credentials delivered through the Amazon EC2 metadata service

**Comment by dwijnand** [comment]
@fiadliel Sure. But did you mean drop the override/anonymous access piece as well?

**Comment by fiadliel** [comment]
I'd prefer to encourage correct use of credentials; do you have a particular use case in mind to keep this (the override)?

**Comment by dwijnand** [comment]
Just sounded like a reasonable fallback, but I'm not fussed.

**Comment by dwijnand** [comment]
Yep. Updated and pushed.

**Comment by fiadliel** [comment]
👍

**Pull request merged**
