### PR TITLE
Remove version check as it stops it being run on java 8

### PR DESCRIPTION
**Pull request by benhutchison**

### CODE REVIEW

**Comment by benhutchison** [comment]
sbt-javaversioncheck plugin was already removed in the commit.

Why is enforcing a minimum bytecode version required, and related to this PR? Why cant people build on jdk 1.6? 

And if you do enforce a minimum, why not use 1.8 which is what [Lambda runs](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)?

**Comment by gheine** [comment]
This is about what java version the sbt plugin is built with and not about the version of a project that the plugin is used in. Currently the plugin is compiled against Java 7, so it can be used in sbt projects that are at least on that level. Removing that restriction would potentially break the plugin for people that use it in projects on java 7.

**Comment by benhutchison** [comment]
Pushed an update, but the conflicting version check changes in `build.sbt` suggest that supporting people on 1.7 wasn't a goal after all

**Comment by fiadliel** [comment]
Actually, I was merging that, and missed the change. I plan to revert it.

Compiling with Java 1.7 is only a cost to the plugin maintainers, not to users of the plugin. In return, it gives potential use of the plugin to a larger set of users.

Once we have to link with a library that is compiled with Java 8 bytecode (or library calls), then the attempt to maintain compatibility is no longer possible, but until then, it still seems useful.

The flags above (changing scalacOptions and javacOptions) is not a "solution" I like, because it doesn't warn one of the possibility of accidentally linking against an API call that only exists on Java 8.

**Comment by fiadliel** [comment]
Can you say what the issue is with using Java 1.7? To reiterate, this changes nothing about the runtime environment, just the way in which the plugin is compiled.

Compiling with Java 7: means compatibility for people using Java 7 or Java 8
Compiling with Java 8: means compatibility only for people using Java 8

**Pull request closed without merging**
